#!/bin/bash -l
#PBS -N carmaccm
#PBS -j oe
#PBS -q ccm_queue
#PBS -l mppwidth=24,walltime=10:00

cd $PBS_O_WORKDIR

if [ $NERSC_HOST = "hopper" ]; then
  module swap PrgEnv-pgi PrgEnv-intel
fi

CRAY_ROOTFS=DSL

module load ccm openmpi_ccm mkl_ccm

./run.sh
